SHELL = /usr/bin/env bash
.SHELLFLAGS = -ecuo pipefail
MAKEFLAGS += --warn-undefined-variables
MAKEFLAGS += --no-builtin-rules
MAKEFLAGS += --no-builtin-variables
.DEFAULT_GOAL := help

# Bump version variables
DRYRUN ?= "false"

# Devcontainer variables
FEATURES ?= common-utils ## Feature to test. Default: 'common-utils'. Options: 'aws-cli', 'common-utils', 'docker-in-docker', 'docker-outside-of-docker', 'terraform'
BASE_IMAGE ?= archlinux:base ## Base image for testing. Must be Arch Linux with 'pacman'. Default: 'archlinux:base'.
PATH_TO_RUN ?= . ## Path to run the tests. Default: . (current directory). Change this in the Makefile or in the environment.
FEATURES_FILTER ?= ## Filter for features. Default: empty. Change this in the Makefile or in the environment.
PRESERVE_TESTCONTAINERS ?= false ## Preserve test containers. Default: false. Change this in the Makefile or in the environment.

# Devcontainer command
DC=yarn devcontainer
DC_TEST=$(DC) features test

# Devcontainer flags
DC_TEST_GLOBAL_FLAGS=--global-scenarios-only
DC_TEST_AUTOGENERATED_FLAGS=--skip-scenarios -f $(FEATURES) -i $(BASE_IMAGE)
DC_TEST_SCENARIOS_FLAGS=-f $(FEATURES) \
	--skip-autogenerated \
	--skip-duplicated \
	--filter $(FEATURES_FILTER) \
	--preserve-test-containers $(PRESERVE_TESTCONTAINERS)

SCRIPTSDIR=./scripts

## Testing:
.PHONY: test-global
test-global: ## Run global scenario tests.
	$(DC_TEST) $(DC_TEST_GLOBAL_FLAGS) $(PATH_TO_RUN)

.PHONY: test-autogenerated
test-autogenerated: ## Run autogenerated tests for a specific feature against a base image. Arguments: FEATURES, BASE_IMAGE.
	$(DC_TEST) $(DC_TEST_AUTOGENERATED_FLAGS) $(PATH_TO_RUN)

.PHONY: test-scenarios
test-scenarios: ## Run scenario tests for a specific feature. Argument: FEATURES.
	$(DC_TEST) $(DC_TEST_SCENARIOS_FLAGS) $(PATH_TO_RUN)

## Build:
.PHONY: upgrade-lockfiles
upgrade-lockfiles: ## Run upgrade_lockfiles.sh script. Arguments: DRYRUN.
	chmod +x $(SCRIPTSDIR)/upgrade_lockfiles.sh
	$(SCRIPTSDIR)/upgrade_lockfiles.sh $(DRYRUN)

## Help:
.PHONY: help
help: GREEN  := $(shell tput -Txterm setaf 2)
help: YELLOW := $(shell tput -Txterm setaf 3)
help: CYAN   := $(shell tput -Txterm setaf 6)
help: RESET  := $(shell tput -Txterm sgr0)
help: ## Show this help
	@echo ''
	@echo 'Usage:'
	@echo '  ${YELLOW}make${RESET} ${GREEN}<target>${RESET}'
	@echo ''
	@echo 'Targets:'
	@awk 'BEGIN {FS = ":.*?## "} { \
		if (/^[a-zA-Z0-9_\/-]+:.*?##.*$$/) {printf "    ${YELLOW}%-20s${GREEN}%s${RESET}\n", $$1, $$2} \
		else if (/^## .*$$/) {printf "  ${CYAN}%s${RESET}\n", substr($$1,4)} \
		}' $(MAKEFILE_LIST)