name: 'Release'
on:
    workflow_dispatch:
    workflow_run:
        workflows: ['Tests']
        types:
            - completed

jobs:
    release:
        name: 'Release'
        if: ${{github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'}}
        runs-on: ubuntu-latest
        permissions:
            contents: write
            issues: write
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Setup Node.js
              uses: bartventer/devcontainer-images/.github/actions/setup-node@v2.3.0
            - name: Import GPG key
              uses: crazy-max/ghaction-import-gpg@v6
              with:
                  gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
                  passphrase: ${{ secrets.GPG_PASSPHRASE }}
            - name: 'Run semantic-release'
              run: yarn run semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
